server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: haproxy-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: haproxy
          __path__: /var/log/haproxy/haproxy/*.log
  - job_name: haproxy-stdout
    static_configs:
      - targets:
          - localhost
        labels:
          job: haproxy
          __path__: /var/log/host/docker.log
  - job_name: modsecurity-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: modsecurity
          __path__: /var/log/modsecurity/*.log
